[package]
name = "zetta"
description = "A modern replacement for ls"
authors = ["Benjamin Sago <ogham@bsago.me>", "Denis Cornehl <denis@cornehl.org>"]
categories = ["command-line-utilities"]
edition = "2021"
rust-version = "1.63.0"
exclude = ["/devtools/*", "/Justfile", "/Vagrantfile", "/screenshots.png"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/syphar/zetta"
version = "0.11.2"


[[bin]]
name = "zetta"


[dependencies]
ansi_term = "0.12"
glob = "0.3"
lazy_static = "1.3"
libc = "0.2"
locale = "0.2"
log = "0.4"
natord = "1.0"
num_cpus = "1.10"
number_prefix = "0.4"
scoped_threadpool = "0.1"
term_grid = "0.2.0"
terminal_size = "0.1.16"
timeago = { version = "0.3.1", default-features = false }
unicode-width = "0.1"
zoneinfo_compiled = "0.5.1"

[target.'cfg(unix)'.dependencies]
users = "0.11"

[dependencies.datetime]
version = "0.5.2"
default-features = false
features = ["format"]

[dependencies.git2]
version = "0.13"
optional = true
default-features = false

[build-dependencies.datetime]
version = "0.5.2"
default-features = false

[features]
default = [ "git" ]
git = [ "git2" ]
vendored-openssl = ["git2/vendored-openssl"]


# make dev builds faster by excluding debug symbols
[profile.dev]
debug = false

# use LTO for smaller binaries (that take longer to build)
[profile.release]
lto = true


[package.metadata.deb]
license-file = [ "LICENCE", "4" ]
depends = "$auto"
extended-description = """
zetta is a replacement for ls written in Rust.
"""
section = "utils"
priority = "optional"
assets = [
    [ "target/release/zetta", "/usr/bin/zetta", "0755" ],
    [ "target/release/../man/zetta.1", "/usr/share/man/man1/zetta.1", "0644" ],
    [ "target/release/../man/zetta_colors.5", "/usr/share/man/man5/zetta_colors.5", "0644" ],
    [ "completions/bash/zetta", "/usr/share/bash-completion/completions/zetta", "0644" ],
    [ "completions/zsh/_zetta", "/usr/share/zsh/site-functions/_zetta", "0644" ],
    [ "completions/fish/zetta.fish", "/usr/share/fish/vendor_completions.d/zetta.fish", "0644" ],
]
